# Site settings
name: your name here
title: title of your blog here
email: your email here
description: "A description of your blog here."
twitter_username: your twitter username
github_username:  your github username

# Build settings
markdown: kramdown
permalinks: pretty
