# Site settings
name: test
email: test1
job_title: test2
institution: test3
institution_URL: test4
baseurl: "" # not sure if we'll use this
url: "" # https://username.github.io
twitter_username: test5
github_username: test6

# Build settings
markdown: kramdown
permalinks: pretty